FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml /app/
COPY README.md /app/         
COPY src /app/src

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir .

EXPOSE 8501
CMD ["streamlit", "run", "src/cineflow/dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
